sudo: required
services:
  - docker

before_install:
  - docker build -t comeanddancewithme/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run comeanddancewithme/react-test npm test -- --coverage

after_success:
  - docker build -t comeanddancewithme/multi-client ./client
  - docker build -t comeanddancewithme/multi-nginx ./nginx
  - docker build -t comeanddancewithme/multi-server ./server
  - docker build -t comeanddancewithme/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push comeanddancewithme/multi-client
  - docker push comeanddancewithme/multi-nginx
  - docker push comeanddancewithme/multi-server
  - docker push comeanddancewithme/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-094462471592
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY